function calcularNivel(vitorias, derrotas) {

    let saldoDeVitorias = vitorias - derrotas;
    let nivel;

    if (vitorias < 10 ){
        nivel = "Ferro";
    } else if(vitorias >= 11 && vitorias <= 20){
        nivel = "Bronze";
    } else if(vitorias >= 21 && vitorias <= 50){
        nivel = "Prata";
    } else if(vitorias >= 51 && vitorias <= 80){
        nivel = "Ouro";
    } else if(vitorias >= 81 && vitorias <= 90){
        nivel = "Diamante";
    } else if(vitorias >= 91 && vitorias <= 100){
        nivel = "Lendário";
    } else if (vitorias >= 101) {
        nivel = "Imortal"
    }
    return "O Herói tem saldo de " + saldoDeVitorias +  " está no nível de " + nivel;
}
let vitorias = 85;
let derrotas = 20;
let resultado = calcularNivel(vitorias, derrotas);
Console.log(resultado); // Exibe: "O Herói tem saldo de 65 está no nível de Ouro"
